# Generated by Django 4.2.1 on 2023-05-30 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='刪除標記')),
                ('content', models.CharField(default='', help_text='評論内容', max_length=500, verbose_name='評論内容')),
                ('rate', models.SmallIntegerField(blank=True, choices=[(1, '好評'), (2, '中評'), (3, '差評')], default=1, help_text='評論級別', verbose_name='評論級別')),
                ('star', models.SmallIntegerField(blank=True, choices=[(1, '一星'), (2, '二星'), (3, '三星'), (4, '四星'), (5, '五星')], default=5, help_text='評論星級', verbose_name='評論星級')),
            ],
            options={
                'verbose_name': '訂單評論',
                'verbose_name_plural': '訂單評論',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='刪除標記')),
                ('addr', models.CharField(help_text='收貨地址', max_length=200, verbose_name='收貨地址')),
                ('order_code', models.CharField(help_text='訂單編號', max_length=50, verbose_name='訂單編號')),
                ('amount', models.FloatField(help_text='訂單總金額', verbose_name='訂單總金額')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '代發貨'), (3, '配送中'), (4, '待評價'), (5, '已完成'), (6, '已關閉')], default=1, help_text='訂單狀態', verbose_name='訂單狀態')),
                ('pay_type', models.SmallIntegerField(blank=True, choices=[(1, '支付寶'), (2, '微信支付'), (3, '雲閃付'), (4, '貨到付款')], help_text='支付方式', null=True, verbose_name='支付方式')),
                ('pay_time', models.DateTimeField(blank=True, help_text='支付時間', null=True, verbose_name='支付時間')),
                ('trade_no', models.CharField(blank=True, help_text='支付單號', max_length=50, null=True, verbose_name='支付單號')),
            ],
            options={
                'verbose_name': '訂單表',
                'verbose_name_plural': '訂單表',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='刪除標記')),
                ('price', models.IntegerField(help_text='商品價格', verbose_name='商品價格')),
                ('number', models.IntegerField(default=1, help_text='商品數量', verbose_name='商品數量')),
                ('goods', models.ForeignKey(help_text='商品ID', on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品ID')),
                ('order', models.ForeignKey(help_text='所屬訂單', on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='所屬訂單')),
            ],
            options={
                'verbose_name': '訂單詳情',
                'verbose_name_plural': '訂單詳情',
                'db_table': 'orderGoods',
            },
        ),
    ]
