# Generated by Django 4.2.1 on 2023-05-30 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='下單用戶', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下單用戶'),
        ),
        migrations.AddField(
            model_name='comment',
            name='goods',
            field=models.ForeignKey(help_text='所屬商品', on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='所屬商品'),
        ),
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(help_text='所屬訂單', on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='所屬訂單'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='評論用戶', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='評論用戶'),
        ),
    ]
