# Generated by Django 4.2.1 on 2023-05-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='刪除標記')),
                ('number', models.SmallIntegerField(blank=True, default=1, help_text='商品數量', verbose_name='商品數量')),
                ('is_checked', models.BooleanField(blank=True, default=True, help_text='是否選中', verbose_name='是否選中')),
            ],
            options={
                'verbose_name': '購物車',
                'verbose_name_plural': '購物車',
                'db_table': 'cart',
            },
        ),
    ]
